about:
  home: www.walberla.net
  license: GPLv3
package:
  name: walberla
  version: 2016.07.01.dev0
requirements:
  build:
  - git
  - boost ==1.58.0 [linux]
  - boost [win]
  - cmake
  - gcc [linux]
  - mpich2 [linux]
  run:
  - boost ==1.58.0 [linux]
  - boost [win]
  - numpy
  - mpich2 [linux]
source:
  git_rev: master
  git_url: git@i10git.cs.fau.de:software/walberla.git
