package:
   name: walberla
   version: 1.0.0

build:
   number: 2

source:
   git_url: git@i10git.cs.fau.de:software/walberla.git
   git_rev: master

requirements:
   build:
      - git
      - boost ==1.58.0
      - cmake
      - gcc
      - mpich2
   run:
      - boost ==1.58.0
      - numpy
      - mpich2

about:
   home: www.walberla.net
   license: GPL3
