about:
  home: www.walberla.net
  license: GPLv3
package:
  name: walberla
  version: 2017.03.28.dev0
requirements:
  build:
  - python >=3.6
  - git
  - boost
  - cmake
  - gcc [linux]
  - mpich2 [linux]
  run:
  - python >=3.6
  - boost
  - numpy
  - mpich2 [linux]
source:
  git_rev: master
  git_url: git@i10git.cs.fau.de:software/walberla.git
