package:
   name: walberla
   version: 1.0.0

build:
   number: 2

source:
   git_url: git@i10git.cs.fau.de:software/walberla.git
   git_rev: master

requirements:
   build:
      - git
      - boost ==1.58.0 [linux]
      - boost [win]
      - cmake
      - gcc [linux]
      - mpich2 [linux]
   run:
      - boost ==1.58.0 [linux]
      - boost [win]
      - numpy
      - mpich2 [linux]
about:
   home: www.walberla.net
   license: GPL3
