FROM ubuntu:20.04
MAINTAINER Chris Watts <chris@cjwatts.com>

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    automake \
    build-essential \
    ccache \
    cmake \ 
    curl \
    doxygen \
    git \
    gnupg \
    graphviz \
    libboost-dev \
    libboost-filesystem-dev \
    libboost-program-options-dev \
    libboost-regex-dev \
    libboost-system-dev \
    libboost-thread-dev \
    liblzma-dev \
    libbz2-dev \
    libicu-dev \
    python3-dev \
    python3-pip \
    python3-numpy \
    libboost-python-dev \    
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* 

ENV CCACHE_DIR=/ccache

