package:
   name: lammps
   version: icms

build:
   number: 2

source:
   git_url: https://github.com/lammps/lammps.git
   git_rev: lammps-icms
   patches: 
      - AddMakefile.patch

 
requirements:
   build:
      - git
      - gcc
      - libpng
      - jpeg
      - mpich2
      - python
   run:
      - libpng
      - jpeg
      - mpich2
      - python

about:
   home: www.walberla.net
   license: GPL3
